#!/bin/bash
token="$(cat ~/.emulator_console_auth_token)"
# expose android 6060 to listen on
echo "cat $token\nredir add udp:9060:9060\nredir list" | telnet localhost 5554

# proxy local 6066 to PS4'
sudo socat -d -v UDP4-LISTEN:9066,reuseaddr,fork UDP4:192.168.0.14:9066